language: node_js
os: linux
node_js:
  - node
  - 'lts/*'
  - '10'
services:
  - postgresql
  - redis-server
before_script:
  - psql -U postgres -d postgres -c 'create database test'
env:
  - PGDATABASE=test
script:
  - 'npm run lint'
  - 'npm test'
cache: npm
notifications:
  email:
    on_success: never
